name: CI/CD with Docker

on:
  push:
    branches:
      - master  # Déclenche le workflow lorsque des commits sont poussés sur la branche main
  pull_request:
    branches:
      - master  # Déclenche le workflow lorsque des pull requests sont ouvertes vers la branche main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Installer les dépendances
      run: npm install
    
    - name: Vérifier les permissions des fichiers Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Lancer les tests
      run: npm test
      continue-on-error: false

    - name: Connexion à Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construire l'image Docker
      if: success()  # Condition : construire l'image seulement si les tests réussissent
      run: docker build -t loriclannister/simple-web-app:latest .

    - name: Pousser l'image Docker vers Docker Hub
      run: docker push loriclannister/simple-web-app:latest